### ISSUE TITLE
Error: 'Authentication' object has no attribute 'dashboard_access'

### ISSUE THREAD

**Issue by qbzenker** [svix/svix-webhooks#1898]
## Bug Report

Hi,

In version 1.64.1 (python client) I try:

```py
svix_client.authentication.dashboard_access(app_id)
```

but get the following error:

```
2025-04-21T10:27:25 INFO [svix_client.py:96] 
Failed to get dashboard details for app_id: org_bfx. 
Error: 'Authentication' object has no attribute 'dashboard_access'
```

It works in version 1.64.0.

Wondering how to fix it, and thinking it should be a minor version change, as opposed to patch, if this is indeed intended depreciation. Thanks!

**Comment by qbzenker** [comment]
Ah OK - we will switch to `app_portal_access` - thank you!
